### ISSUE TITLE
Sf3.3 compatibility ?

### ISSUE THREAD

**Issue by xorgxx** [asprega/BreadcrumbBundle#1]
Hi, 
i m having same probleme all since to work well in this : 

```
/**
 * Notification controller.
 * @Breadcrumb({
 *     {"label" = "administration", "route" = "admin_index" },
 *     {"label" = "notification" }
 *     })
 * @Route("notification")
 */
class NotificationCrudController extends Controller

```
but it having probleme in this : 

```
/**
 * Page controller.
 * @Breadcrumb({
 *     {"label" = "Page" }
 *     })
 * @Route("/page")
 */
class PageCrudController extends AbstractController
.......

    /**
     * Creates a new page entity.
     * @Breadcrumb({"label" = "[new]" })
     * @Route("/new", name="admin_page_crud_new")
     * @Method({"GET", "POST"})
     * @Secure(roles="ROLE_SUPER_ADMIN")
     */
    public function newAction(Request $request)
```

is taking only `[new]` das not take `Page`

thank for your help.

**Comment by asprega** [comment]
Hi! Are you using the latest version (0.1.3)?

I wasn't able to reproduce your issue, I'm pretty sure it might have been a bug in a previous version.

**Comment by xorgxx** [comment]
Hi, yes i m using ver 0.1.3

**Comment by xorgxx** [comment]
soory, maybe i was not clear it work well on must of all page! but not with class` PageCrudController extends AbstractController`

**Comment by asprega** [comment]
Closing for lack of steps to reproduce the failure. Please re-open if still an issue with version 0.2.0.
