### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by julienduthoit** [asprega/BreadcrumbBundle#4]
Hi, 

I have a problem using the asprega_breadrumb() twig function in my template on the last version of Symfony.
![image](https://user-images.githubusercontent.com/685799/54599759-95e74b80-4a3b-11e9-8be8-f75da379fc5d.png)

I followed the instructions to install the bundle but did I miss something?

Thanks,

**Comment by julienduthoit** [comment]
I succeeded by adding 
`asprega_breadcrumb:
    template: owntemplate.html.twig`
into my services.yaml and copying the initial template into it.

Thanks

**Comment by asprega** [comment]
Hi Julien.

You're right, I need to update documentation and code to the newest Symfony conventions. Will create a release soon, glad that in the meanwhile you found the workaround. Thanks!
