### ISSUE TITLE
Class 'Twig_Extension' not found in Symfony 5

### ISSUE THREAD

**Issue by medy36** [asprega/BreadcrumbBundle#9]
I am trying to install your bundle in a Symfony 5 project.

The installation failed at :
```
 Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]

 [critical] Fatal Error: Class 'Twig_Extension' not found in  vendor/asprega/breadcrumb-bundle/Twig/BreadcrumbExtension.php on line 8

```
Is an upgrade conceivable for this compatibility?

**Comment by asprega** [comment]
Hi! Sorry it took so long. Please try out the new 0.5.0 release and feel free to re-open an issue if needed. Thanks!

https://github.com/asprega/BreadcrumbBundle/releases/tag/0.5.0
